"""product name no longer unique

Revision ID: 35a9f198a215
Revises: c864fa900d10
Create Date: 2020-07-30 21:59:14.610404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a9f198a215'
down_revision = 'c864fa900d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_product_name', table_name='products')
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.create_index('ix_products_product_name', 'products', ['product_name'], unique=1)
    # ### end Alembic commands ###
