"""add new column

Revision ID: c864fa900d10
Revises: 
Create Date: 2020-07-26 09:10:11.966263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c864fa900d10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('detail_information', sa.String(length=512), nullable=True),
    sa.Column('category', sa.Enum('Skincare Products', 'Makeups', 'Lipsticks', 'Others', name='Category'), nullable=True),
    sa.Column('photo', sa.String(length=64), nullable=True),
    sa.Column('profile_photo', sa.String(length=64), nullable=True),
    sa.Column('popular', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo'),
    sa.UniqueConstraint('profile_photo')
    )
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
